name: Hassfest Action
on:
  push:
    branches: [main]
  pull_request:
jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
      - name: Hassfest
        uses: "home-assistant/actions/hassfest@master"
